### PR TITLE
chore(utils): specify msrv of 1.87

### LINKED ISSUE #1580: Crates should mention msrv when possible
https://github.com/commonwarexyz/monorepo/pull/1454 introduced the use of https://doc.rust-lang.org/stable/std/primitive.usize.html#method.unbounded_shr, which requires rust version >= 1.87.

Adding msrv to crates' Cargo.tomls is helpful to users who don't necessarily want to be running rust nightly version.

### PR DESCRIPTION
**Pull request by samlaf**
(Partially) Closes #1580 

This is needed by the unbounded_shr function that was introduced in https://github.com/commonwarexyz/monorepo/pull/1454

When trying to build `examples/sync`:
```
$ cargo +1.86 build
...
error[E0658]: use of unstable library feature `unbounded_shifts`
   --> utils/src/bitvec.rs:322:51
    |
322 |             n if n < BITS_PER_BLOCK => FULL_BLOCK.unbounded_shr((BITS_PER_BLOCK - n) as u32),
    |                                                   ^^^^^^^^^^^^^
    |
    = note: see issue #129375 <https://github.com/rust-lang/rust/issues/129375> for more information
```

With the msrv mentioned in utils:
```
$ cargo +1.86 build
error: rustc 1.86.0 is not supported by the following package:
  commonware-utils@0.0.62 requires rustc 1.87
```

### CODE REVIEW

File: utils/Cargo.toml [hunk 1]
```diff
@@ -3,6 +3,8 @@ name = "commonware-utils"
 edition.workspace = true
 publish = true
 version.workspace = true
+# We use https://doc.rust-lang.org/stable/std/primitive.usize.html#method.unbounded_shr
+rust-version = "1.87"
```
Comment (patrick-ogrady) [inline utils/Cargo.toml:7]: It would be great to specify this in the root cargo.toml and use `rust-version.workspace`?

Comment (samlaf) [reply utils/Cargo.toml:7]: I was assuming that not all crates depend on utils so some might have lower actual msrv. But might not be worth the maintenance headache to have separate msrv per crate either… your call ill make the change if you want.

Comment (patrick-ogrady) [reply utils/Cargo.toml:7]: I'm new to specifying msrv, so need to ponder.

We strongly prefer to keep things like this unified tho.

Comment (clabby) [reply utils/Cargo.toml:7]: Generally sharing MSRV across the whole workspace makes life a lot easier imo.

**Comment by clabby** [comment]
Thanks for opening this PR! We're closing it as stale for now, but we'd be happy to take another look if you rebase and reopen it.
